services:
  postfix:
    # testing this using this command line:
    # curl -v smtp://0.0.0.0:25 --mail-from myself@example.com --mail-rcpt receiver@example.com --upload-file test-mail.txt
    image: rothan/docker-postfix:dev
    ports:
    - "25:25"
    env_file:
      - .env
    environment:
    - RELAY_MYNETWORKS=true
    - TRANSPORT_MAP_FILE=/etc/postfix-config/transport
    - SMTP_SERVER=fast-srv04.fn.terra4d.de
    - SMTP_PORT=25
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - ./test-config:/etc/postfix-config

